import { useCallback, useEffect, useMemo, useRef, useState } from "react";
import Navbar from "@/components/Navbar";
import { Button } from "@/components/ui/button";
import { Card, CardContent } from "@/components/ui/card";
import { Input } from "@/components/ui/input";
import { Textarea } from "@/components/ui/textarea";
import { Badge } from "@/components/ui/badge";
import {
  Play,
  Loader2,
  ChevronLeft,
  ChevronRight,
  RotateCcw,
  Eye,
  Languages as LanguagesIcon,
  Sparkles,
  Download,
} from "lucide-react";
import { supabase } from "@/integrations/supabase/client";
import { toast } from "@/hooks/use-toast";
import { cn } from "@/lib/utils";
import { pinyin } from "pinyin-pro";
import { scorePronunciation, type ScoreResult } from "@/lib/pronunciationScore";
import YouTubeSegmentPlayer, { type YouTubeSegmentPlayerHandle } from "@/components/YouTubeSegmentPlayer";

interface Segment {
  idx: number;
  start: number;
  dur: number;
  hanzi: string;
}

interface VideoData {
  videoId: string;
  title: string;
  languageCode: string;
  isAutoGenerated: boolean;
  segments: Segment[];
}

const RATES = [0.75, 1, 1.25] as const;

const extractVideoId = (input: string): string | null => {
  const s = input.trim();
  if (!s) return null;
  if (/^[\w-]{6,15}$/.test(s)) return s;
  try {
    const u = new URL(s);
    if (u.hostname.includes("youtu.be")) {
      return u.pathname.slice(1).split("/")[0] || null;
    }
    if (u.hostname.includes("youtube.com")) {
      const v = u.searchParams.get("v");
      if (v) return v;
      const parts = u.pathname.split("/").filter(Boolean);
      const idx = parts.findIndex((p) => p === "embed" || p === "shorts" || p === "live");
      if (idx >= 0 && parts[idx + 1]) return parts[idx + 1];
    }
  } catch { /* noop */ }
  return null;
};

const fmtTime = (s: number) => {
  const m = Math.floor(s / 60);
  const r = Math.floor(s % 60);
  return `${m}:${r.toString().padStart(2, "0")}`;
};

const STORAGE_KEY = "hskhub:dictation:state";

interface PersistedState {
  videoId: string;
  data: VideoData;
  scores: Record<number, ScoreResult>;
  inputs: Record<number, string>;
  currentIdx: number;
}

const Dictation = () => {
  const [url, setUrl] = useState("");
  const [loading, setLoading] = useState(false);
  const [data, setData] = useState<VideoData | null>(null);
  const [currentIdx, setCurrentIdx] = useState(0);
  const [inputs, setInputs] = useState<Record<number, string>>({});
  const [scores, setScores] = useState<Record<number, ScoreResult>>({});
  const [showAnswer, setShowAnswer] = useState<Record<number, boolean>>({});
  const [showPinyin, setShowPinyin] = useState<Record<number, boolean>>({});
  const [translations, setTranslations] = useState<Record<number, string>>({});
  const [translatingIdx, setTranslatingIdx] = useState<number | null>(null);
  const [rate, setRate] = useState<number>(1);
  const playerRef = useRef<YouTubeSegmentPlayerHandle>(null);

  // Restore last session
  useEffect(() => {
    try {
      const raw = localStorage.getItem(STORAGE_KEY);
      if (!raw) return;
      const s = JSON.parse(raw) as PersistedState;
      if (s?.data?.segments?.length) {
        setData(s.data);
        setUrl(`https://www.youtube.com/watch?v=${s.videoId}`);
        setScores(s.scores ?? {});
        setInputs(s.inputs ?? {});
        setCurrentIdx(s.currentIdx ?? 0);
      }
    } catch { /* noop */ }
  }, []);

  // Persist
  useEffect(() => {
    if (!data) return;
    const s: PersistedState = {
      videoId: data.videoId,
      data,
      scores,
      inputs,
      currentIdx,
    };
    try { localStorage.setItem(STORAGE_KEY, JSON.stringify(s)); } catch { /* noop */ }
  }, [data, scores, inputs, currentIdx]);

  const handleLoad = async () => {
    const videoId = extractVideoId(url);
    if (!videoId) {
      toast({ title: "URL không hợp lệ", description: "Hãy dán link YouTube hợp lệ.", variant: "destructive" });
      return;
    }
    setLoading(true);
    try {
      const { data: res, error } = await supabase.functions.invoke("youtube-captions", {
        body: { videoId },
      });
      if (error) throw new Error(error.message);
      if (res?.error) throw new Error(res.error);
      const vd = res as VideoData;
      setData(vd);
      setCurrentIdx(0);
      setScores({});
      setInputs({});
      setShowAnswer({});
      setShowPinyin({});
      setTranslations({});
      toast({
        title: "Đã tải phụ đề",
        description: `${vd.segments.length} câu · ${vd.isAutoGenerated ? "Auto-generated" : "Phụ đề thủ công"}`,
      });
    } catch (e) {
      const msg = e instanceof Error ? e.message : String(e);
      toast({ title: "Không tải được phụ đề", description: msg, variant: "destructive" });
    } finally {
      setLoading(false);
    }
  };

  const seg = data?.segments[currentIdx];

  const playCurrent = useCallback(() => {
    if (!seg) return;
    playerRef.current?.setRate(rate);
    playerRef.current?.playSegment(seg.start, seg.dur);
  }, [seg, rate]);

  const checkAnswer = () => {
    if (!seg) return;
    const input = inputs[currentIdx] ?? "";
    if (!input.trim()) {
      toast({ title: "Hãy gõ câu bạn nghe được", variant: "destructive" });
      return;
    }
    const result = scorePronunciation(seg.hanzi, input);
    setScores((p) => ({ ...p, [currentIdx]: result }));
  };

  const resetCurrent = () => {
    setScores((p) => { const n = { ...p }; delete n[currentIdx]; return n; });
    setInputs((p) => ({ ...p, [currentIdx]: "" }));
    setShowAnswer((p) => ({ ...p, [currentIdx]: false }));
  };

  const togglePinyin = () => setShowPinyin((p) => ({ ...p, [currentIdx]: !p[currentIdx] }));
  const toggleAnswer = () => setShowAnswer((p) => ({ ...p, [currentIdx]: !p[currentIdx] }));

  const fetchTranslation = async () => {
    if (!seg) return;
    if (translations[currentIdx]) return;
    setTranslatingIdx(currentIdx);
    try {
      const { data: res, error } = await supabase.functions.invoke("dictation-translate", {
        body: { text: seg.hanzi },
      });
      if (error) throw new Error(error.message);
      if (res?.error) throw new Error(res.error);
      setTranslations((p) => ({ ...p, [currentIdx]: res.translation as string }));
    } catch (e) {
      const msg = e instanceof Error ? e.message : String(e);
      toast({ title: "Không dịch được", description: msg, variant: "destructive" });
    } finally {
      setTranslatingIdx(null);
    }
  };

  const goPrev = () => setCurrentIdx((i) => Math.max(0, i - 1));
  const goNext = () => {
    if (!data) return;
    setCurrentIdx((i) => Math.min(data.segments.length - 1, i + 1));
  };

  const currentScore = scores[currentIdx];
  const currentPinyin = useMemo(
    () => (seg ? pinyin(seg.hanzi, { toneType: "symbol", v: true }) : ""),
    [seg]
  );

  const avgScore = useMemo(() => {
    const keys = Object.keys(scores);
    if (!keys.length) return null;
    return Math.round(keys.reduce((a, k) => a + scores[Number(k)].total, 0) / keys.length);
  }, [scores]);

  const handleRateChange = (r: number) => {
    setRate(r);
    playerRef.current?.setRate(r);
  };

  return (
    <div className="min-h-screen bg-background">
      <Navbar />
      <main className="container mx-auto max-w-5xl px-4 py-6">
        <header className="mb-4">
          <h1 className="font-serif text-2xl font-bold gold-text md:text-3xl">听写 · Chép chính tả từ YouTube</h1>
          <p className="text-sm text-muted-foreground">
            Dán link video YouTube tiếng Trung có phụ đề. App sẽ tách thành từng câu để bạn nghe và chép lại.
          </p>
        </header>

        {/* URL input */}
        <Card className="mb-4">
          <CardContent className="flex flex-col gap-3 p-4 sm:flex-row">
            <Input
              placeholder="https://www.youtube.com/watch?v=..."
              value={url}
              onChange={(e) => setUrl(e.target.value)}
              onKeyDown={(e) => e.key === "Enter" && handleLoad()}
              className="flex-1"
            />
            <Button onClick={handleLoad} disabled={loading} className="gap-2">
              {loading ? <Loader2 className="h-4 w-4 animate-spin" /> : <Download className="h-4 w-4" />}
              Tải phụ đề
            </Button>
          </CardContent>
        </Card>

        {data && seg && (
          <>
            {/* Player */}
            <div className="mb-4">
              <YouTubeSegmentPlayer ref={playerRef} videoId={data.videoId} />
              {data.title && (
                <p className="mt-2 truncate text-sm text-muted-foreground" title={data.title}>
                  {data.title}{" "}
                  {data.isAutoGenerated && (
                    <Badge variant="outline" className="ml-1 text-[10px]">auto-caption</Badge>
                  )}
                </p>
              )}
            </div>

            {/* Current segment card */}
            <Card className="mb-4">
              <CardContent className="space-y-4 p-4">
                <div className="flex flex-wrap items-center gap-2">
                  <Badge variant="secondary">
                    Câu {currentIdx + 1} / {data.segments.length}
                  </Badge>
                  <span className="text-xs text-muted-foreground">
                    {fmtTime(seg.start)} → {fmtTime(seg.start + seg.dur)} · {seg.dur.toFixed(1)}s
                  </span>
                  <div className="ml-auto flex items-center gap-1">
                    {RATES.map((r) => (
                      <Button
                        key={r}
                        size="sm"
                        variant={rate === r ? "default" : "outline"}
                        className="h-7 px-2 text-xs"
                        onClick={() => handleRateChange(r)}
                      >
                        {r}x
                      </Button>
                    ))}
                  </div>
                </div>

                <Button onClick={playCurrent} className="w-full gap-2" size="lg">
                  <Play className="h-4 w-4" />
                  Nghe câu này
                </Button>

                <Textarea
                  placeholder="Gõ những gì bạn nghe được (汉字)..."
                  value={inputs[currentIdx] ?? ""}
                  onChange={(e) => setInputs((p) => ({ ...p, [currentIdx]: e.target.value }))}
                  onKeyDown={(e) => {
                    if (e.key === "Enter" && (e.ctrlKey || e.metaKey)) checkAnswer();
                  }}
                  className="min-h-[80px] text-lg"
                />

                <div className="flex flex-wrap gap-2">
                  <Button onClick={checkAnswer} variant="default" size="sm" className="gap-1">
                    <Sparkles className="h-4 w-4" />
                    Kiểm tra
                  </Button>
                  <Button onClick={toggleAnswer} variant="outline" size="sm" className="gap-1">
                    <Eye className="h-4 w-4" />
                    {showAnswer[currentIdx] ? "Ẩn đáp án" : "Hiện đáp án"}
                  </Button>
                  <Button onClick={togglePinyin} variant="outline" size="sm" className="gap-1">
                    拼
                    {showPinyin[currentIdx] ? " Ẩn pinyin" : " Pinyin"}
                  </Button>
                  <Button
                    onClick={fetchTranslation}
                    variant="outline"
                    size="sm"
                    className="gap-1"
                    disabled={translatingIdx === currentIdx}
                  >
                    {translatingIdx === currentIdx ? (
                      <Loader2 className="h-4 w-4 animate-spin" />
                    ) : (
                      <LanguagesIcon className="h-4 w-4" />
                    )}
                    Nghĩa VN
                  </Button>
                  {currentScore && (
                    <Button onClick={resetCurrent} variant="ghost" size="sm" className="gap-1">
                      <RotateCcw className="h-4 w-4" />
                      Thử lại
                    </Button>
                  )}
                </div>

                {/* Reveal blocks */}
                {showAnswer[currentIdx] && (
                  <div className="rounded-md border border-border/60 bg-muted/30 p-3">
                    <p className="text-xs text-muted-foreground">Đáp án:</p>
                    <p className="text-lg">{seg.hanzi}</p>
                  </div>
                )}
                {showPinyin[currentIdx] && (
                  <div className="rounded-md border border-border/60 bg-muted/30 p-3">
                    <p className="text-xs text-muted-foreground">Pinyin:</p>
                    <p className="text-base">{currentPinyin}</p>
                  </div>
                )}
                {translations[currentIdx] && (
                  <div className="rounded-md border border-border/60 bg-muted/30 p-3">
                    <p className="text-xs text-muted-foreground">Nghĩa tiếng Việt:</p>
                    <p className="text-base italic">{translations[currentIdx]}</p>
                  </div>
                )}

                {/* Score */}
                {currentScore && (
                  <div className="space-y-2 rounded-md border border-primary/30 bg-primary/5 p-3">
                    <div className="flex flex-wrap items-center gap-3 text-sm">
                      <span>So sánh ký tự:</span>
                      <p className="text-lg">
                        {currentScore.hanziDiff.map((d, i) => (
                          <span
                            key={i}
                            className={cn(
                              d.status === "match" ? "text-emerald-500" : "text-red-500 underline"
                            )}
                          >
                            {d.char}
                          </span>
                        ))}
                      </p>
                      <span
                        className={cn(
                          "ml-auto rounded px-2 py-1 text-base font-bold",
                          currentScore.total >= 80
                            ? "bg-emerald-500/20 text-emerald-500"
                            : currentScore.total >= 50
                              ? "bg-amber-500/20 text-amber-500"
                              : "bg-red-500/20 text-red-500"
                        )}
                      >
                        {currentScore.total}%
                      </span>
                    </div>
                  </div>
                )}
              </CardContent>
            </Card>

            {/* Nav */}
            <div className="flex items-center justify-between gap-2">
              <Button variant="outline" onClick={goPrev} disabled={currentIdx === 0} className="gap-1">
                <ChevronLeft className="h-4 w-4" />
                Câu trước
              </Button>
              <span className="text-sm text-muted-foreground">
                Tiến độ: {Object.keys(scores).length}/{data.segments.length}
                {avgScore !== null && (
                  <>
                    {" · "}
                    Điểm TB: <strong className="text-foreground">{avgScore}%</strong>
                  </>
                )}
              </span>
              <Button
                variant="outline"
                onClick={goNext}
                disabled={currentIdx === data.segments.length - 1}
                className="gap-1"
              >
                Câu tiếp
                <ChevronRight className="h-4 w-4" />
              </Button>
            </div>
          </>
        )}

        {!data && !loading && (
          <Card>
            <CardContent className="p-6 text-sm text-muted-foreground">
              <p className="mb-2 font-medium text-foreground">Gợi ý:</p>
              <ul className="list-disc space-y-1 pl-5">
                <li>Chọn video tiếng Trung có phụ đề 中文 (ưu tiên phụ đề thủ công, không phải auto-caption).</li>
                <li>Video tin tức CCTV, vlog, phim hoạt hình HSK… đều phù hợp.</li>
                <li>Nếu video không có sub tiếng Trung, app sẽ báo lỗi — hãy thử video khác.</li>
                <li>Có thể giảm tốc độ phát còn 0.75x nếu nghe khó.</li>
              </ul>
            </CardContent>
          </Card>
        )}
      </main>
    </div>
  );
};

export default Dictation;
