import { useCallback, useEffect, useMemo, useRef, useState } from "react";
import Navbar from "@/components/Navbar";
import { Button } from "@/components/ui/button";
import { Card, CardContent } from "@/components/ui/card";
import { Input } from "@/components/ui/input";
import { Textarea } from "@/components/ui/textarea";
import { Badge } from "@/components/ui/badge";
import { Tabs, TabsList, TabsTrigger, TabsContent } from "@/components/ui/tabs";
import { Tooltip, TooltipTrigger, TooltipContent, TooltipProvider } from "@/components/ui/tooltip";
import {
  Play,
  Loader2,
  ChevronLeft,
  ChevronRight,
  RotateCcw,
  Eye,
  Languages as LanguagesIcon,
  Sparkles,
  Download,
  ArrowLeft,
  Keyboard,
  CheckCircle,
  Trophy,
} from "lucide-react";
import { supabase } from "@/integrations/supabase/client";
import { toast } from "@/hooks/use-toast";
import { cn } from "@/lib/utils";
import { pinyin } from "pinyin-pro";
import { normalizeHanzi, scorePronunciation, type ScoreResult } from "@/lib/pronunciationScore";
import YouTubeSegmentPlayer, { type YouTubeSegmentPlayerHandle } from "@/components/YouTubeSegmentPlayer";
import {
  DICTATION_VIDEOS,
  DICTATION_CATEGORIES,
  DICTATION_LEVELS,
  LEVEL_COLORS,
  getThumbnail,
  type DictationCategory,
  type DictationLevel,
  type DictationVideo,
} from "@/data/dictationVideos";

interface Segment {
  idx: number;
  start: number;
  dur: number;
  hanzi: string;
}

interface VideoData {
  videoId: string;
  title: string;
  languageCode: string;
  isAutoGenerated: boolean;
  segments: Segment[];
  translations?: string[];
}

const RATES = [0.75, 1, 1.25] as const;

const extractVideoId = (input: string): string | null => {
  const s = input.trim();
  if (!s) return null;
  if (/^[\w-]{6,15}$/.test(s)) return s;
  try {
    const u = new URL(s);
    if (u.hostname.includes("youtu.be")) {
      return u.pathname.slice(1).split("/")[0] || null;
    }
    if (u.hostname.includes("youtube.com")) {
      const v = u.searchParams.get("v");
      if (v) return v;
      const parts = u.pathname.split("/").filter(Boolean);
      const idx = parts.findIndex((p) => p === "embed" || p === "shorts" || p === "live");
      if (idx >= 0 && parts[idx + 1]) return parts[idx + 1];
    }
  } catch { /* noop */ }
  return null;
};

const fmtTime = (s: number) => {
  const m = Math.floor(s / 60);
  const r = Math.floor(s % 60);
  return `${m}:${r.toString().padStart(2, "0")}`;
};

const STORAGE_KEY = "hskhub:dictation:state";

interface PersistedState {
  videoId: string;
  data: VideoData;
  scores: Record<number, ScoreResult>;
  inputs: Record<number, string>;
  currentIdx: number;
}

const Dictation = () => {
  const [url, setUrl] = useState("");
  const [loading, setLoading] = useState(false);
  const [data, setData] = useState<VideoData | null>(null);
  const [currentIdx, setCurrentIdx] = useState(0);
  const [inputs, setInputs] = useState<Record<number, string>>({});
  const [scores, setScores] = useState<Record<number, ScoreResult>>({});
  const [hints, setHints] = useState<Record<number, number>>({});
  const [showAnswer, setShowAnswer] = useState<Record<number, boolean>>({});
  const [showPinyin, setShowPinyin] = useState<Record<number, boolean>>({});
  const [translations, setTranslations] = useState<Record<number, string>>({});
  const [translatingIdx, setTranslatingIdx] = useState<number | null>(null);
  const [rate, setRate] = useState<number>(1);
  const [completed, setCompleted] = useState(false);
  const [levelFilter, setLevelFilter] = useState<DictationLevel | "all">("all");
  const [categoryFilter, setCategoryFilter] = useState<DictationCategory | "all">("all");
  const playerRef = useRef<YouTubeSegmentPlayerHandle>(null);
  const textareaRef = useRef<HTMLTextAreaElement>(null);

  // Timestamps đã được forced-align bằng Soniox; chỉ pad nhẹ đuôi để khỏi cụt.
  const AUDIO_OFFSET = 0; // giây
  const PLAYBACK_PAD_END = 0.2;

  // Restore last session
  useEffect(() => {
    try {
      const raw = localStorage.getItem(STORAGE_KEY);
      if (!raw) return;
      const s = JSON.parse(raw) as PersistedState;
      if (s?.data?.segments?.length) {
        // Rehydrate translations từ thư viện curated nếu localStorage cũ chưa có
        const curated = DICTATION_VIDEOS.find((v) => v.youtubeId === s.videoId);
        const merged: VideoData = {
          ...s.data,
          translations: s.data.translations ?? curated?.translations,
        };
        setData(merged);
        setUrl(`https://www.youtube.com/watch?v=${s.videoId}`);
        setScores(s.scores ?? {});
        setInputs(s.inputs ?? {});
        setCurrentIdx(s.currentIdx ?? 0);
      }
    } catch { /* noop */ }
  }, []);

  // Persist
  useEffect(() => {
    if (!data) return;
    const s: PersistedState = {
      videoId: data.videoId,
      data,
      scores,
      inputs,
      currentIdx,
    };
    try { localStorage.setItem(STORAGE_KEY, JSON.stringify(s)); } catch { /* noop */ }
  }, [data, scores, inputs, currentIdx]);

  const hasAutoStartedRef = useRef(false);

  const resetAll = () => {
    setScores({});
    setHints({});
    setInputs({});
    setShowAnswer({});
    setShowPinyin({});
    setTranslations({});
    setCompleted(false);
  };

  const loadVideoId = async (videoId: string) => {
    setLoading(true);
    try {
      // 1) Nếu video có phụ đề curated nhúng sẵn → dùng luôn, tránh phụ thuộc
      //    edge function (YouTube đang chặn IP của Edge Runtime).
      const curated = DICTATION_VIDEOS.find((v) => v.youtubeId === videoId);
      if (curated?.segments?.length) {
        const vd: VideoData = {
          videoId,
          title: curated.titleVi || curated.title,
          languageCode: curated.languageCode ?? "zh-Hans",
          isAutoGenerated: curated.isAutoGenerated ?? false,
          segments: curated.segments,
          translations: curated.translations,
        };
        setData(vd);
        resetAll();
        if (vd.segments.length > 1) {
          hasAutoStartedRef.current = true;
          setCurrentIdx(1);
        } else {
          setCurrentIdx(0);
        }
        toast({
          title: "Đã tải phụ đề",
          description: `${vd.segments.length} câu · Phụ đề có sẵn`,
        });
        return;
      }

      const { data: res, error } = await supabase.functions.invoke("youtube-captions", {
        body: { videoId },
      });
      if (error) throw new Error(error.message);
      if (res?.error) throw new Error(res.error);
      const vd = res as VideoData;
      setData(vd);
      resetAll();
      if (vd.segments.length > 1) {
        hasAutoStartedRef.current = true;
        setCurrentIdx(1);
      } else {
        setCurrentIdx(0);
      }
      toast({
        title: "Đã tải phụ đề",
        description: `${vd.segments.length} câu · ${vd.isAutoGenerated ? "Auto-generated" : "Phụ đề thủ công"}`,
      });
    } catch (e) {
      const msg = e instanceof Error ? e.message : String(e);
      toast({ title: "Không tải được phụ đề", description: msg, variant: "destructive" });
    } finally {
      setLoading(false);
    }
  };

  const handleLoadUrl = () => {
    const videoId = extractVideoId(url);
    if (!videoId) {
      toast({ title: "URL không hợp lệ", description: "Hãy dán link YouTube hợp lệ.", variant: "destructive" });
      return;
    }
    loadVideoId(videoId);
  };

  const handlePickLibrary = (v: DictationVideo) => {
    setUrl(`https://www.youtube.com/watch?v=${v.youtubeId}`);
    loadVideoId(v.youtubeId);
  };

  const handleChangeVideo = () => {
    setData(null);
    try { localStorage.removeItem(STORAGE_KEY); } catch { /* noop */ }
    hasAutoStartedRef.current = false;
    resetAll();
    setCurrentIdx(0);
    setCompleted(false);
  };

  const seg = data?.segments[currentIdx];

  const playCurrent = useCallback(() => {
    if (!seg) return;
    playerRef.current?.setRate(rate);
    const start = Math.max(0, seg.start + AUDIO_OFFSET);
    const dur = seg.dur + PLAYBACK_PAD_END;
    playerRef.current?.playSegment(start, dur);
  }, [seg, rate]);

  const goPrev = useCallback(() => setCurrentIdx((i) => Math.max(0, i - 1)), []);
  const goNext = useCallback(() => {
    setCurrentIdx((i) => {
      const max = (data?.segments.length ?? 1) - 1;
      return Math.min(max, i + 1);
    });
  }, [data]);

  const checkAnswer = useCallback(() => {
    if (!seg) return;
    const input = inputs[currentIdx] ?? "";
    if (!input.trim()) {
      toast({ title: "Hãy gõ câu bạn nghe được", variant: "destructive" });
      return;
    }
    const result = scorePronunciation(seg.hanzi, input);
    setScores((p) => ({ ...p, [currentIdx]: result }));
    const normalizedAnswer = normalizeHanzi(seg.hanzi);
    const normalizedInput = normalizeHanzi(input);
    const allCorrect = normalizedAnswer.length > 0 && normalizedInput === normalizedAnswer;
    if (allCorrect) {
      setHints((p) => { const n = { ...p }; delete n[currentIdx]; return n; });
      // Hiển thị đáp án đầy đủ + dịch, chờ Enter tiếp theo để qua câu kế.
      setShowAnswer((p) => ({ ...p, [currentIdx]: true }));
      void fetchTranslation();
    } else {
      // Tìm tiền tố đúng dài nhất, hiển thị thêm 1 chữ kế tiếp ở khu so sánh
      let prefix = 0;
      while (
        prefix < normalizedInput.length &&
        prefix < normalizedAnswer.length &&
        normalizedInput[prefix] === normalizedAnswer[prefix]
      ) {
        prefix++;
      }
      if (prefix < normalizedAnswer.length) {
        setHints((p) => ({ ...p, [currentIdx]: prefix + 1 }));
      }
    }
    return result;
  }, [seg, inputs, currentIdx]);

  const resetCurrent = () => {
    setScores((p) => { const n = { ...p }; delete n[currentIdx]; return n; });
    setHints((p) => { const n = { ...p }; delete n[currentIdx]; return n; });
    setInputs((p) => ({ ...p, [currentIdx]: "" }));
    setShowAnswer((p) => ({ ...p, [currentIdx]: false }));
  };

  const togglePinyin = () => setShowPinyin((p) => ({ ...p, [currentIdx]: !p[currentIdx] }));
  const toggleAnswer = () => setShowAnswer((p) => ({ ...p, [currentIdx]: !p[currentIdx] }));

  const fetchTranslation = async () => {
    if (!seg || !data) return;
    if (translations[currentIdx]) return;
    // Ưu tiên bản dịch dựng sẵn (script translate-dictation.ts)
    const preset = data.translations?.[currentIdx];
    if (preset) {
      setTranslations((p) => ({ ...p, [currentIdx]: preset }));
      return;
    }
    setTranslatingIdx(currentIdx);
    try {
      const { data: res, error } = await supabase.functions.invoke("dictation-translate", {
        body: { text: seg.hanzi },
      });
      if (error) throw new Error(error.message);
      if (res?.error) throw new Error(res.error);
      setTranslations((p) => ({ ...p, [currentIdx]: res.translation as string }));
    } catch (e) {
      const msg = e instanceof Error ? e.message : String(e);
      toast({ title: "Không dịch được", description: msg, variant: "destructive" });
    } finally {
      setTranslatingIdx(null);
    }
  };


  // Keyboard shortcuts
  // - Ctrl/Cmd alone (press + release without other key) → replay current segment
  // - Ctrl/Cmd + ArrowLeft / ArrowRight → prev / next
  // - Enter (in textarea, no Shift) handled separately in Textarea onKeyDown
  useEffect(() => {
    if (!data || !seg) return;
    let ctrlAlone = false;

    const onKeyDown = (e: KeyboardEvent) => {
      if (e.key === "Control" || e.key === "Meta") {
        if (!e.repeat) ctrlAlone = true;
        return;
      }
      // any other key pressed → not Ctrl-alone anymore
      ctrlAlone = false;

      if ((e.ctrlKey || e.metaKey) && e.key === "ArrowRight") {
        e.preventDefault();
        goNext();
      } else if ((e.ctrlKey || e.metaKey) && e.key === "ArrowLeft") {
        e.preventDefault();
        goPrev();
      }
    };

    const onKeyUp = (e: KeyboardEvent) => {
      if ((e.key === "Control" || e.key === "Meta") && ctrlAlone) {
        ctrlAlone = false;
        playCurrent();
      }
    };

    const onBlur = () => { ctrlAlone = false; };

    window.addEventListener("keydown", onKeyDown);
    window.addEventListener("keyup", onKeyUp);
    window.addEventListener("blur", onBlur);
    return () => {
      window.removeEventListener("keydown", onKeyDown);
      window.removeEventListener("keyup", onKeyUp);
      window.removeEventListener("blur", onBlur);
    };
  }, [data, seg, playCurrent, goNext, goPrev]);

  // Auto-play segment 1 when a video is first loaded (skip intro/title segment 0)
  useEffect(() => {
    if (!data || !seg || !hasAutoStartedRef.current) return;
    hasAutoStartedRef.current = false;
    const timer = setTimeout(() => {
      playCurrent();
    }, 700);
    return () => clearTimeout(timer);
  }, [data, seg, playCurrent]);

  const isCurrentCorrect = useMemo(() => {
    if (!seg) return false;
    const ans = normalizeHanzi(seg.hanzi);
    const inp = normalizeHanzi(inputs[currentIdx] ?? "");
    return ans.length > 0 && inp === ans;
  }, [seg, inputs, currentIdx]);

  const handleTextareaKeyDown = (e: React.KeyboardEvent<HTMLTextAreaElement>) => {
    if (e.key === "Enter" && !e.shiftKey && !e.ctrlKey && !e.metaKey) {
      e.preventDefault();
      if (isCurrentCorrect && showAnswer[currentIdx]) {
        const next = data?.segments[currentIdx + 1];
        goNext();
        if (next) {
          setTimeout(() => {
            playerRef.current?.setRate(rate);
            playerRef.current?.playSegment(
              Math.max(0, next.start + AUDIO_OFFSET),
              next.dur + PLAYBACK_PAD_END
            );
          }, 200);
        }
      } else {
        checkAnswer();
      }
    }
  };

  const currentScore = scores[currentIdx];
  const currentPinyin = useMemo(
    () => (seg ? pinyin(seg.hanzi, { toneType: "symbol", v: true }) : ""),
    [seg]
  );

  const avgScore = useMemo(() => {
    const keys = Object.keys(scores);
    if (!keys.length) return null;
    return Math.round(keys.reduce((a, k) => a + scores[Number(k)].total, 0) / keys.length);
  }, [scores]);

  const handleRateChange = (r: number) => {
    setRate(r);
    playerRef.current?.setRate(r);
  };

  const filteredVideos = useMemo(() => {
    return DICTATION_VIDEOS.filter((v) =>
      (levelFilter === "all" || v.level === levelFilter) &&
      (categoryFilter === "all" || v.category === categoryFilter)
    );
  }, [levelFilter, categoryFilter]);

  return (
    <div className="min-h-screen bg-background">
      <Navbar />
      <main className="container mx-auto max-w-7xl px-4 py-6">
        <header className="mb-4">
          <h1 className="font-serif text-2xl font-bold gold-text md:text-3xl">听写 · Chép chính tả từ YouTube</h1>
          <p className="text-sm text-muted-foreground">
            Chọn video từ thư viện hoặc dán link YouTube tiếng Trung. App tách thành từng câu để bạn nghe và chép lại.
          </p>
        </header>

        {!data && (
          <Tabs defaultValue="library" className="mb-4">
            <TabsList>
              <TabsTrigger value="library">Thư viện</TabsTrigger>
              <TabsTrigger value="url">Dán link</TabsTrigger>
            </TabsList>

            <TabsContent value="library" className="space-y-4">
              <Card>
                <CardContent className="space-y-3 p-4">
                  <div className="flex flex-wrap gap-2">
                    <span className="text-xs text-muted-foreground self-center mr-1">Cấp độ:</span>
                    <Button
                      size="sm"
                      variant={levelFilter === "all" ? "default" : "outline"}
                      onClick={() => setLevelFilter("all")}
                      className="h-7 px-2 text-xs"
                    >Tất cả</Button>
                    {DICTATION_LEVELS.map((lv) => (
                      <Button
                        key={lv.id}
                        size="sm"
                        variant={levelFilter === lv.id ? "default" : "outline"}
                        onClick={() => setLevelFilter(lv.id)}
                        className="h-7 px-2 text-xs"
                      >{lv.label}</Button>
                    ))}
                  </div>
                  <div className="flex flex-wrap gap-2">
                    <span className="text-xs text-muted-foreground self-center mr-1">Chủ đề:</span>
                    <Button
                      size="sm"
                      variant={categoryFilter === "all" ? "default" : "outline"}
                      onClick={() => setCategoryFilter("all")}
                      className="h-7 px-2 text-xs"
                    >Tất cả</Button>
                    {DICTATION_CATEGORIES.map((c) => (
                      <Button
                        key={c.id}
                        size="sm"
                        variant={categoryFilter === c.id ? "default" : "outline"}
                        onClick={() => setCategoryFilter(c.id)}
                        className="h-7 px-2 text-xs"
                      >{c.label}</Button>
                    ))}
                  </div>
                </CardContent>
              </Card>

              {filteredVideos.length === 0 ? (
                <Card>
                  <CardContent className="p-6 text-sm text-muted-foreground">
                    {DICTATION_VIDEOS.length === 0 ? (
                      <>
                        <p className="mb-2 font-medium text-foreground">Thư viện đang trống.</p>
                        <p>Thêm video vào <code className="rounded bg-muted px-1">src/data/dictationVideos.ts</code> để hiển thị ở đây, hoặc dùng tab "Dán link" để luyện tạm.</p>
                      </>
                    ) : (
                      <p>Không có video nào khớp với bộ lọc.</p>
                    )}
                  </CardContent>
                </Card>
              ) : (
                <div className="grid grid-cols-1 gap-3 sm:grid-cols-2 lg:grid-cols-3">
                  {filteredVideos.map((v) => (
                    <button
                      key={v.id}
                      onClick={() => handlePickLibrary(v)}
                      disabled={loading}
                      className="group overflow-hidden rounded-lg border border-border/60 bg-card text-left transition hover:border-primary/60 hover:shadow-md disabled:opacity-50"
                    >
                      <div className="relative aspect-video w-full overflow-hidden bg-muted">
                        <img
                          src={getThumbnail(v)}
                          alt={v.title}
                          className="h-full w-full object-cover transition group-hover:scale-105"
                          loading="lazy"
                        />
                        {v.durationLabel && (
                          <span className="absolute bottom-1 right-1 rounded bg-black/70 px-1.5 py-0.5 text-[10px] text-white">
                            {v.durationLabel}
                          </span>
                        )}
                      </div>
                      <div className="space-y-1.5 p-3">
                        <div className="flex flex-wrap items-center gap-1.5">
                          <Badge variant="outline" className={cn("text-[10px]", LEVEL_COLORS[v.level])}>
                            {DICTATION_LEVELS.find((l) => l.id === v.level)?.short}
                          </Badge>
                          <Badge variant="outline" className="text-[10px]">
                            {DICTATION_CATEGORIES.find((c) => c.id === v.category)?.label}
                          </Badge>
                        </div>
                        <p className="line-clamp-2 text-sm font-medium">{v.title}</p>
                        {v.titleVi && (
                          <p className="line-clamp-1 text-xs text-muted-foreground">{v.titleVi}</p>
                        )}
                      </div>
                    </button>
                  ))}
                </div>
              )}
            </TabsContent>

            <TabsContent value="url">
              <Card>
                <CardContent className="flex flex-col gap-3 p-4 sm:flex-row">
                  <Input
                    placeholder="https://www.youtube.com/watch?v=..."
                    value={url}
                    onChange={(e) => setUrl(e.target.value)}
                    onKeyDown={(e) => e.key === "Enter" && handleLoadUrl()}
                    className="flex-1"
                  />
                  <Button onClick={handleLoadUrl} disabled={loading} className="gap-2">
                    {loading ? <Loader2 className="h-4 w-4 animate-spin" /> : <Download className="h-4 w-4" />}
                    Tải phụ đề
                  </Button>
                </CardContent>
              </Card>
            </TabsContent>
          </Tabs>
        )}

        {data && seg && (
          <>
            <div className="mb-3 flex items-center justify-between gap-2">
              <Button variant="ghost" size="sm" onClick={handleChangeVideo} className="gap-1">
                <ArrowLeft className="h-4 w-4" /> Đổi video
              </Button>
              <div className="flex items-center gap-1 text-xs text-muted-foreground">
                <Keyboard className="h-3.5 w-3.5" />
                <span className="hidden sm:inline">
                  <kbd className="rounded bg-muted px-1">Ctrl</kbd> nghe lại ·{" "}
                  <kbd className="rounded bg-muted px-1">Enter</kbd> nộp ·{" "}
                  <kbd className="rounded bg-muted px-1">Ctrl</kbd>+<kbd className="rounded bg-muted px-1">←</kbd>/<kbd className="rounded bg-muted px-1">→</kbd> chuyển câu
                </span>
              </div>
            </div>

            {/* Split: video bên trái, controls/đáp án bên phải */}
            <div className="grid gap-4 lg:grid-cols-2">
              <div className="space-y-2 lg:sticky lg:top-4 lg:self-start">
                <YouTubeSegmentPlayer ref={playerRef} videoId={data.videoId} />
                {data.title && (
                  <p className="truncate text-sm text-muted-foreground" title={data.title}>
                    {data.title}{" "}
                    {data.isAutoGenerated && (
                      <Badge variant="outline" className="ml-1 text-[10px]">auto-caption</Badge>
                    )}
                  </p>
                )}
              </div>

              <div className="space-y-4">

            {/* Current segment card */}
            <Card className="mb-4">
              <CardContent className="space-y-4 p-4">
                <div className="flex flex-wrap items-center gap-2">
                  <Badge variant="secondary">
                    Câu {currentIdx + 1} / {data.segments.length}
                  </Badge>
                  <span className="text-xs text-muted-foreground">
                    {fmtTime(seg.start)} → {fmtTime(seg.start + seg.dur)} · {seg.dur.toFixed(1)}s
                  </span>
                  <div className="ml-auto flex items-center gap-1">
                    {RATES.map((r) => (
                      <Button
                        key={r}
                        size="sm"
                        variant={rate === r ? "default" : "outline"}
                        className="h-7 px-2 text-xs"
                        onClick={() => handleRateChange(r)}
                      >
                        {r}x
                      </Button>
                    ))}
                  </div>
                </div>

                <Button onClick={playCurrent} className="w-full gap-2" size="lg">
                  <Play className="h-4 w-4" />
                  Nghe câu này (Ctrl)
                </Button>

                <Textarea
                  ref={textareaRef}
                  placeholder="Gõ những gì bạn nghe được (汉字)... Enter để nộp, Shift+Enter để xuống dòng"
                  value={inputs[currentIdx] ?? ""}
                  onChange={(e) => setInputs((p) => ({ ...p, [currentIdx]: e.target.value }))}
                  onKeyDown={handleTextareaKeyDown}
                  className="min-h-[80px] text-lg"
                />

                <div className="flex flex-wrap gap-2">
                  <Button onClick={checkAnswer} variant="default" size="sm" className="gap-1">
                    <Sparkles className="h-4 w-4" />
                    Kiểm tra
                  </Button>
                  <Button onClick={toggleAnswer} variant="outline" size="sm" className="gap-1">
                    <Eye className="h-4 w-4" />
                    {showAnswer[currentIdx] ? "Ẩn đáp án" : "Hiện đáp án"}
                  </Button>
                  <Button onClick={togglePinyin} variant="outline" size="sm" className="gap-1">
                    拼
                    {showPinyin[currentIdx] ? " Ẩn pinyin" : " Pinyin"}
                  </Button>
                  <Button
                    onClick={fetchTranslation}
                    variant="outline"
                    size="sm"
                    className="gap-1"
                    disabled={translatingIdx === currentIdx}
                  >
                    {translatingIdx === currentIdx ? (
                      <Loader2 className="h-4 w-4 animate-spin" />
                    ) : (
                      <LanguagesIcon className="h-4 w-4" />
                    )}
                    Nghĩa VN
                  </Button>
                  {currentScore && (
                    <Button onClick={resetCurrent} variant="ghost" size="sm" className="gap-1">
                      <RotateCcw className="h-4 w-4" />
                      Thử lại
                    </Button>
                  )}
                </div>

                {showAnswer[currentIdx] && (
                  <div className="rounded-md border border-border/60 bg-muted/30 p-3">
                    <p className="text-xs text-muted-foreground">Đáp án:</p>
                    <p className="text-lg">{seg.hanzi}</p>
                  </div>
                )}
                {showPinyin[currentIdx] && (
                  <div className="rounded-md border border-border/60 bg-muted/30 p-3">
                    <p className="text-xs text-muted-foreground">Pinyin:</p>
                    <p className="text-base">{currentPinyin}</p>
                  </div>
                )}
                {translations[currentIdx] && (
                  <div className="rounded-md border border-border/60 bg-muted/30 p-3">
                    <p className="text-xs text-muted-foreground">Nghĩa tiếng Việt:</p>
                    <p className="text-base italic">{translations[currentIdx]}</p>
                  </div>
                )}

                {currentScore && (() => {
                  const answerChars = normalizeHanzi(seg.hanzi).split("");
                  const userChars = normalizeHanzi(inputs[currentIdx] ?? "").split("");
                  let matchedLen = 0;
                  while (
                    matchedLen < answerChars.length &&
                    matchedLen < userChars.length &&
                    answerChars[matchedLen] === userChars[matchedLen]
                  ) matchedLen++;
                  const revealLen = hints[currentIdx] ?? 0;
                  return (
                    <div className="space-y-2 rounded-md border border-primary/30 bg-primary/5 p-3">
                      <div className="flex flex-wrap items-center gap-3 text-sm">
                        <span>So sánh ký tự:</span>
                        <TooltipProvider delayDuration={100}>
                          <p className="text-lg">
                            {answerChars.map((ch, i) => {
                              if (i < matchedLen) {
                                return <span key={i} className="text-emerald-500">{ch}</span>;
                              }
                              if (i < revealLen) {
                                return (
                                  <span
                                    key={i}
                                    className="rounded bg-amber-500/15 px-0.5 text-amber-600 underline decoration-dotted"
                                    title="Gợi ý chữ tiếp theo"
                                  >
                                    {ch}
                                  </span>
                                );
                              }
                              return (
                                <Tooltip key={i}>
                                  <TooltipTrigger asChild>
                                    <span className="cursor-help rounded bg-red-500/15 px-0.5 text-red-500 underline decoration-dotted">
                                      ▢
                                    </span>
                                  </TooltipTrigger>
                                  <TooltipContent side="top">
                                    <span className="font-serif text-base">{ch}</span>
                                  </TooltipContent>
                                </Tooltip>
                              );
                            })}
                          </p>
                        </TooltipProvider>
                        <span
                          className={cn(
                            "ml-auto rounded px-2 py-1 text-base font-bold",
                            currentScore.total >= 80
                              ? "bg-emerald-500/20 text-emerald-500"
                              : currentScore.total >= 50
                                ? "bg-amber-500/20 text-amber-500"
                                : "bg-red-500/20 text-red-500"
                          )}
                        >
                          {currentScore.total}%
                        </span>
                      </div>
                      <p className="text-xs text-muted-foreground">
                        <span className="text-emerald-500">Xanh</span>: đúng ·{" "}
                        <span className="text-amber-600">Vàng</span>: gợi ý chữ tiếp theo ·{" "}
                        <span className="text-red-500">▢</span>: chỗ còn lại (rê chuột để xem).
                      </p>
                    </div>
                  );
                })()}
              </CardContent>
            </Card>

            <div className="flex items-center justify-between gap-2">
              <Button variant="outline" onClick={goPrev} disabled={currentIdx === 0} className="gap-1">
                <ChevronLeft className="h-4 w-4" />
                Câu trước
              </Button>
              <span className="text-sm text-muted-foreground">
                Tiến độ: {Object.keys(scores).length}/{data.segments.length}
                {avgScore !== null && (
                  <>
                    {" · "}
                    Điểm TB: <strong className="text-foreground">{avgScore}%</strong>
                  </>
                )}
              </span>
              <Button
                variant="outline"
                onClick={goNext}
                disabled={currentIdx === data.segments.length - 1}
                className="gap-1"
              >
                Câu tiếp
                <ChevronRight className="h-4 w-4" />
              </Button>
            </div>
              </div>
            </div>
          </>

        )}
      </main>
    </div>
  );
};

export default Dictation;
