// AUTO-GENERATED by @lovable.dev/mcp-js — do not edit. Regenerated by the Vite plugin.
// To take ownership, delete this banner line; the plugin then leaves the file alone.
// supabase function: mcp
// Bundled from src/lib/mcp/index.ts by @lovable.dev/mcp-js.
// src/lib/mcp/index.ts
import { auth, defineMcp } from "npm:@lovable.dev/mcp-js@0.24.0";

// src/lib/mcp/tools/search-vocabulary.ts
import { defineTool } from "npm:@lovable.dev/mcp-js@0.24.0";
import { z } from "npm:zod@^3.25.76";
import { allVocab, getVocabByLevel } from "npm:@/data/vocab";
var search_vocabulary_default = defineTool({
  name: "search_vocabulary",
  title: "Search HSK vocabulary",
  description: "Search the HSK 1-6 vocabulary bank of HSK Hub by hanzi, pinyin or English meaning. Optionally filter by HSK level.",
  inputSchema: {
    query: z.string().describe("Hanzi, pinyin or English meaning to search for. Leave empty to browse by level."),
    level: z.number().int().optional().describe("HSK level filter, 1 to 6."),
    limit: z.number().int().optional().describe("Maximum number of words to return (default 20, max 100).")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: ({ query, level, limit }) => {
    const max = Math.min(Math.max(limit ?? 20, 1), 100);
    const pool = level && level >= 1 && level <= 6 ? getVocabByLevel(level) : allVocab;
    const q = (query ?? "").trim().toLowerCase();
    const matches = (q ? pool.filter(
      (w) => w.hanzi.includes(q) || w.pinyin.toLowerCase().includes(q) || w.meaning.toLowerCase().includes(q)
    ) : pool).slice(0, max);
    const rows = matches.map((w) => ({
      hanzi: w.hanzi,
      pinyin: w.pinyin,
      pos: w.pos,
      meaning: w.meaning,
      level: w.level,
      example: w.example
    }));
    return {
      content: [
        {
          type: "text",
          text: rows.length === 0 ? "No matching vocabulary found." : rows.map((r) => `HSK${r.level} ${r.hanzi} (${r.pinyin}) [${r.pos}] \u2014 ${r.meaning}
  \u4F8B: ${r.example.chinese} \u2014 ${r.example.english}`).join("\n")
        }
      ],
      structuredContent: { count: rows.length, words: rows }
    };
  }
});

// src/lib/mcp/tools/search-grammar.ts
import { defineTool as defineTool2 } from "npm:@lovable.dev/mcp-js@0.24.0";
import { z as z2 } from "npm:zod@^3.25.76";
import { allGrammar, getGrammarByLevel } from "npm:@/data/grammar";
var search_grammar_default = defineTool2({
  name: "search_grammar",
  title: "Search HSK grammar points",
  description: "Search HSK Hub's HSK 1-6 grammar reference by pattern, name or explanation, with structure formula and examples.",
  inputSchema: {
    query: z2.string().describe("Pattern, keyword or English explanation to search for. Leave empty to browse by level."),
    level: z2.number().int().optional().describe("HSK level filter, 1 to 6."),
    limit: z2.number().int().optional().describe("Maximum number of grammar points to return (default 10, max 40).")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: ({ query, level, limit }) => {
    const max = Math.min(Math.max(limit ?? 10, 1), 40);
    const pool = level && level >= 1 && level <= 6 ? getGrammarByLevel(level) : allGrammar;
    const q = (query ?? "").trim().toLowerCase();
    const matches = (q ? pool.filter(
      (g) => g.pattern.toLowerCase().includes(q) || g.name.toLowerCase().includes(q) || g.explanation.toLowerCase().includes(q) || g.structure.toLowerCase().includes(q)
    ) : pool).slice(0, max);
    const rows = matches.map((g) => ({
      level: g.level,
      pattern: g.pattern,
      name: g.name,
      category: g.category,
      structure: g.structure,
      explanation: g.explanation,
      examples: g.examples.slice(0, 3)
    }));
    return {
      content: [
        {
          type: "text",
          text: rows.length === 0 ? "No matching grammar point found." : rows.map(
            (r) => `HSK${r.level} ${r.pattern} \u2014 ${r.name}
  Structure: ${r.structure}
  ${r.explanation}
` + r.examples.map((e) => `  \u4F8B: ${e.chinese} (${e.pinyin}) \u2014 ${e.english}`).join("\n")
          ).join("\n\n")
        }
      ],
      structuredContent: { count: rows.length, grammar: rows }
    };
  }
});

// src/lib/mcp/tools/list-dictation-videos.ts
import { defineTool as defineTool3 } from "npm:@lovable.dev/mcp-js@0.24.0";
import { z as z3 } from "npm:zod@^3.25.76";
import { DICTATION_VIDEOS } from "npm:@/data/dictationVideos";
var list_dictation_videos_default = defineTool3({
  name: "list_dictation_videos",
  title: "List dictation videos",
  description: "Browse HSK Hub's Chinese dictation (\u542C\u5199) library: title, level, topic category, duration and number of practice sentences.",
  inputSchema: {
    query: z3.string().optional().describe("Filter by title text (Chinese or Vietnamese)."),
    level: z3.string().optional().describe("Level filter: beginner, intermediate or advanced."),
    category: z3.string().optional().describe("Category filter: news, vlog, cartoon, drama, education, history, discovery, other."),
    limit: z3.number().int().optional().describe("Maximum number of videos to return (default 25, max 100).")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: ({ query, level, category, limit }) => {
    const max = Math.min(Math.max(limit ?? 25, 1), 100);
    const q = (query ?? "").trim().toLowerCase();
    const rows = DICTATION_VIDEOS.filter((v) => {
      if (level && v.level !== level) return false;
      if (category && v.category !== category) return false;
      if (q && !(v.title.toLowerCase().includes(q) || (v.titleVi ?? "").toLowerCase().includes(q))) return false;
      return true;
    }).slice(0, max).map((v) => ({
      id: v.id,
      title: v.title,
      titleVi: v.titleVi ?? null,
      level: v.level,
      category: v.category,
      durationLabel: v.durationLabel ?? null,
      sentenceCount: v.segments?.length ?? 0,
      youtubeUrl: `https://www.youtube.com/watch?v=${v.youtubeId}`
    }));
    return {
      content: [
        {
          type: "text",
          text: rows.length === 0 ? "No dictation video matched the filters." : rows.map(
            (r) => `${r.title}${r.titleVi ? ` (${r.titleVi})` : ""} \u2014 ${r.level}/${r.category} \xB7 ${r.sentenceCount} sentences${r.durationLabel ? ` \xB7 ${r.durationLabel}` : ""} \xB7 id=${r.id}`
          ).join("\n")
        }
      ],
      structuredContent: { count: rows.length, videos: rows }
    };
  }
});

// src/lib/mcp/tools/get-dictation-transcript.ts
import { defineTool as defineTool4 } from "npm:@lovable.dev/mcp-js@0.24.0";
import { z as z4 } from "npm:zod@^3.25.76";
import { DICTATION_VIDEOS as DICTATION_VIDEOS2 } from "npm:@/data/dictationVideos";
var get_dictation_transcript_default = defineTool4({
  name: "get_dictation_transcript",
  title: "Get dictation transcript",
  description: "Return the sentence-by-sentence Chinese transcript (with Vietnamese translation when available) of one dictation video from HSK Hub. Use list_dictation_videos first to get the video id.",
  inputSchema: {
    videoId: z4.string().describe("The dictation entry id returned by list_dictation_videos."),
    from: z4.number().int().optional().describe("First sentence index to return (0-based, default 0)."),
    count: z4.number().int().optional().describe("How many sentences to return (default 40, max 200).")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: ({ videoId, from, count }) => {
    const video = DICTATION_VIDEOS2.find((v) => v.id === videoId || v.youtubeId === videoId);
    if (!video) {
      return { content: [{ type: "text", text: `No dictation video with id "${videoId}".` }], isError: true };
    }
    const segments = video.segments ?? [];
    const start = Math.max(from ?? 0, 0);
    const take = Math.min(Math.max(count ?? 40, 1), 200);
    const slice = segments.slice(start, start + take).map((s, i) => ({
      index: start + i,
      start: s.start,
      duration: s.dur,
      hanzi: s.hanzi,
      vi: video.translations?.[start + i] ?? null
    }));
    return {
      content: [
        {
          type: "text",
          text: slice.length === 0 ? `"${video.title}" has no prepared transcript in this range.` : `${video.title} (${slice.length}/${segments.length} sentences)
` + slice.map((s) => `${s.index + 1}. [${s.start.toFixed(1)}s] ${s.hanzi}${s.vi ? `
   ${s.vi}` : ""}`).join("\n")
        }
      ],
      structuredContent: {
        videoId: video.id,
        title: video.title,
        totalSentences: segments.length,
        sentences: slice
      }
    };
  }
});

// src/lib/mcp/tools/get-province.ts
import { defineTool as defineTool5 } from "npm:@lovable.dev/mcp-js@0.24.0";
import { z as z5 } from "npm:zod@^3.25.76";
import { PROVINCES } from "npm:@/data/provinces";
var get_province_default = defineTool5({
  name: "get_province",
  title: "Explore a Chinese province",
  description: "Look up one of China's 34 provincial-level units in HSK Hub's \u63A2\u7D22\u4E2D\u56FD dataset: capital, population, area, cuisine, landmarks, universities and the Chinese reading passage when available. Omit the name to list all units.",
  inputSchema: {
    name: z5.string().optional().describe("Province name in Chinese, pinyin or Vietnamese. Omit to list every unit.")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: ({ name }) => {
    const q = (name ?? "").trim().toLowerCase();
    if (!q) {
      const list = PROVINCES.map((p2) => `${p2.nameCn} (${p2.nameVn}) \u2014 ${p2.kind}${p2.capital ? ` \xB7 th\u1EE7 ph\u1EE7 ${p2.capital}` : ""}`);
      return {
        content: [{ type: "text", text: list.join("\n") }],
        structuredContent: { count: PROVINCES.length, provinces: PROVINCES.map((p2) => ({ id: p2.id, nameCn: p2.nameCn, nameVn: p2.nameVn, kind: p2.kind })) }
      };
    }
    const p = PROVINCES.find((x) => x.nameCn.includes(q) || x.geoName.includes(q)) ?? PROVINCES.find(
      (x) => x.namePinyin.toLowerCase().includes(q) || x.nameVn.toLowerCase().includes(q) || x.id.toLowerCase() === q
    );
    if (!p) {
      return { content: [{ type: "text", text: `No provincial-level unit matched "${name}".` }], isError: true };
    }
    const h = p.highlights ?? {};
    const lines = [
      `${p.nameCn} / ${p.geoName} (${p.nameVn}) \u2014 ${p.kind}`,
      p.capital ? `Th\u1EE7 ph\u1EE7: ${p.capital}${p.capitalVn ? ` (${p.capitalVn})` : ""}` : null,
      p.population ? `D\xE2n s\u1ED1: ${p.population}` : null,
      p.area ? `Di\u1EC7n t\xEDch: ${p.area}` : null,
      p.majorCities?.length ? `Th\xE0nh ph\u1ED1 l\u1EDBn: ${p.majorCities.map((c) => `${c.cn} (${c.vn})`).join(", ")}` : null,
      h.cuisine?.length ? `\u1EA8m th\u1EF1c: ${h.cuisine.join(", ")}` : null,
      h.landmarks?.length ? `\u0110\u1ECBa danh: ${h.landmarks.join(", ")}` : null,
      h.universities?.length ? `\u0110\u1EA1i h\u1ECDc: ${h.universities.join(", ")}` : null,
      h.industries?.length ? `Kinh t\u1EBF: ${h.industries.join(", ")}` : null,
      h.famousPeople?.length ? `Nh\xE2n v\u1EADt: ${h.famousPeople.join(", ")}` : null,
      h.historical ? `L\u1ECBch s\u1EED: ${h.historical}` : null,
      p.reading ? `
B\xE0i \u0111\u1ECDc:
${p.reading.cn}

D\u1ECBch:
${p.reading.vn}` : null
    ].filter(Boolean);
    return {
      content: [{ type: "text", text: lines.join("\n") }],
      structuredContent: { province: p }
    };
  }
});

// src/lib/mcp/tools/list-saved-words.ts
import { defineTool as defineTool6 } from "npm:@lovable.dev/mcp-js@0.24.0";
import { z as z6 } from "npm:zod@^3.25.76";

// src/lib/mcp/supabase.ts
import { createClient } from "npm:@supabase/supabase-js@^2.103.3";
function supabaseForUser(ctx) {
  return createClient(process.env.SUPABASE_URL, process.env.SUPABASE_PUBLISHABLE_KEY, {
    global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
    auth: { persistSession: false, autoRefreshToken: false }
  });
}
var notAuthenticated = {
  content: [{ type: "text", text: "Not authenticated. Sign in to HSK Hub through the OAuth flow first." }],
  isError: true
};

// src/lib/mcp/tools/list-saved-words.ts
var list_saved_words_default = defineTool6({
  name: "list_saved_words",
  title: "List my saved words",
  description: "List the signed-in user's saved vocabulary notebook (\u751F\u8BCD\u672C) entries from HSK Hub.",
  inputSchema: {
    limit: z6.number().int().optional().describe("Maximum number of entries to return (default 50, max 200).")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ limit }, ctx) => {
    if (!ctx.isAuthenticated()) return notAuthenticated;
    const max = Math.min(Math.max(limit ?? 50, 1), 200);
    const { data, error } = await supabaseForUser(ctx).from("saved_words").select("id, text, note, created_at").order("created_at", { ascending: false }).limit(max);
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    const rows = data ?? [];
    return {
      content: [
        {
          type: "text",
          text: rows.length === 0 ? "\u751F\u8BCD\u672C is empty." : rows.map((r) => `${r.text}${r.note ? ` \u2014 ${r.note}` : ""}`).join("\n")
        }
      ],
      structuredContent: { count: rows.length, words: rows }
    };
  }
});

// src/lib/mcp/tools/save-word.ts
import { defineTool as defineTool7 } from "npm:@lovable.dev/mcp-js@0.24.0";
import { z as z7 } from "npm:zod@^3.25.76";
var save_word_default = defineTool7({
  name: "save_word",
  title: "Save a word to my notebook",
  description: "Add a Chinese word, phrase or sentence (with an optional note) to the signed-in user's HSK Hub \u751F\u8BCD\u672C.",
  inputSchema: {
    text: z7.string().trim().describe("The Chinese word, phrase or sentence to save."),
    note: z7.string().optional().describe("Optional note, meaning or translation.")
  },
  annotations: { readOnlyHint: false, destructiveHint: false, idempotentHint: true, openWorldHint: false },
  handler: async ({ text, note }, ctx) => {
    if (!ctx.isAuthenticated()) return notAuthenticated;
    const value = text.trim();
    if (!value) return { content: [{ type: "text", text: "text must not be empty." }], isError: true };
    const { data, error } = await supabaseForUser(ctx).from("saved_words").upsert(
      { user_id: ctx.getUserId(), text: value, note: note?.trim() || null },
      { onConflict: "user_id,text" }
    ).select("id, text, note, created_at").maybeSingle();
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return {
      content: [{ type: "text", text: `Saved "${value}" to \u751F\u8BCD\u672C.` }],
      structuredContent: { word: data }
    };
  }
});

// src/lib/mcp/tools/list-exam-results.ts
import { defineTool as defineTool8 } from "npm:@lovable.dev/mcp-js@0.24.0";
import { z as z8 } from "npm:zod@^3.25.76";
var list_exam_results_default = defineTool8({
  name: "list_exam_results",
  title: "List my mock exam results",
  description: "List the signed-in user's HSK mock exam results from HSK Hub, newest first, with score per section.",
  inputSchema: {
    limit: z8.number().int().optional().describe("Maximum number of results to return (default 20, max 100).")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ limit }, ctx) => {
    if (!ctx.isAuthenticated()) return notAuthenticated;
    const max = Math.min(Math.max(limit ?? 20, 1), 100);
    const { data, error } = await supabaseForUser(ctx).from("exam_results").select("exam_id, exam_title, section, total_questions, correct_answers, score_percent, elapsed_seconds, submitted_at").order("submitted_at", { ascending: false }).limit(max);
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    const rows = data ?? [];
    return {
      content: [
        {
          type: "text",
          text: rows.length === 0 ? "No mock exam results yet." : rows.map(
            (r) => `${new Date(r.submitted_at).toISOString().slice(0, 10)} \xB7 ${r.exam_title} \xB7 ${r.section}: ${r.correct_answers}/${r.total_questions} (${r.score_percent}%)`
          ).join("\n")
        }
      ],
      structuredContent: { count: rows.length, results: rows }
    };
  }
});

// src/lib/mcp/index.ts
var projectRef = "tvksbjzilcqofkkrfvug";
var mcp_default = defineMcp({
  name: "hsk-hub-mcp",
  title: "HSK Hub",
  version: "0.1.0",
  instructions: "Tools for HSK Hub, a Chinese learning platform (HSK 1-6 vocabulary and grammar, dictation videos, and a \u63A2\u7D22\u4E2D\u56FD province guide). Use `search_vocabulary` and `search_grammar` for study reference, `list_dictation_videos` plus `get_dictation_transcript` for listening practice material, `get_province` for Chinese culture and geography, and `list_saved_words` / `save_word` / `list_exam_results` to work with the signed-in learner's own notebook and exam history.",
  auth: auth.oauth.issuer({
    issuer: `https://${projectRef}.supabase.co/auth/v1`,
    acceptedAudiences: "authenticated"
  }),
  tools: [
    search_vocabulary_default,
    search_grammar_default,
    list_dictation_videos_default,
    get_dictation_transcript_default,
    get_province_default,
    list_saved_words_default,
    save_word_default,
    list_exam_results_default
  ]
});

// lovable-mcp-supabase-entry.ts
import { createSupabaseHandler } from "npm:@lovable.dev/mcp-js@0.24.0/stacks/supabase";
Deno.serve(createSupabaseHandler(mcp_default, { functionName: "mcp" }));
