export type DictationLevel = "beginner" | "intermediate" | "advanced";
export type DictationCategory =
  | "news"
  | "vlog"
  | "cartoon"
  | "drama"
  | "education"
  | "history"
  | "discovery"
  | "other";

export interface DictationSegment {
  idx: number;
  start: number;
  dur: number;
  hanzi: string;
}

export interface DictationVideo {
  id: string;
  youtubeId: string;
  title: string;
  titleVi?: string;
  level: DictationLevel;
  category: DictationCategory;
  description?: string;
  durationLabel?: string;
  thumbnail?: string;
  /** Phụ đề tiếng Trung dựng sẵn (curated). Khi có, trang Dictation sẽ
   * dùng luôn thay vì gọi edge function (giúp tránh việc YouTube chặn IP). */
  segments?: DictationSegment[];
  languageCode?: string;
  isAutoGenerated?: boolean;
}

export const DICTATION_CATEGORIES: { id: DictationCategory; label: string }[] = [
  { id: "discovery", label: `Kh\u00e1m ph\u00e1` },
  { id: "history", label: `L\u1ecbch s\u1eed` },
  { id: "news", label: `Tin t\u1ee9c` },
  { id: "vlog", label: `Vlog` },
  { id: "cartoon", label: `Ho\u1ea1t h\u00ecnh` },
  { id: "drama", label: `Phim` },
  { id: "education", label: `H\u1ecdc t\u1eadp` },
  { id: "other", label: `Kh\u00e1c` },
];

export const DICTATION_LEVELS: { id: DictationLevel; label: string; short: string }[] = [
  { id: "beginner", label: `S\u01a1 c\u1ea5p`, short: `S\u01a1 c\u1ea5p` },
  { id: "intermediate", label: `Trung c\u1ea5p`, short: `Trung c\u1ea5p` },
  { id: "advanced", label: `Cao c\u1ea5p`, short: `Cao c\u1ea5p` },
];

export const LEVEL_COLORS: Record<DictationLevel, string> = {
  beginner: "bg-emerald-500/15 text-emerald-500 border-emerald-500/30",
  intermediate: "bg-orange-500/15 text-orange-500 border-orange-500/30",
  advanced: "bg-red-500/15 text-red-500 border-red-500/30",
};

// Backward-compatible alias (was named HSK_LEVEL_COLORS)
export const HSK_LEVEL_COLORS = LEVEL_COLORS;

export const getThumbnail = (v: DictationVideo) =>
  v.thumbnail ?? `https://i.ytimg.com/vi/${v.youtubeId}/hqdefault.jpg`;

const SILK_ROAD_SEGMENTS: DictationSegment[] = [
  { idx: 0, start: 6.42, dur: 2.4, hanzi: `\u4e00\u4f4d\u4f26\u6566\u5546\u4eba\u628a\u4ed6\u6700\u65b0\u7684\u80a1\u7968\u4fe1\u606f` },
  { idx: 1, start: 9.06, dur: 3.06, hanzi: `\u5728\u4e0d\u5230\u4e00\u79d2\u7684\u65f6\u95f4\u5185\u53d1\u9001\u5230\u4e86\u4ed6\u5728\u9999\u6e2f\u7684\u540c\u4e8b\u3002` },
  { idx: 2, start: 12.36, dur: 1.74, hanzi: `\u7f8e\u56fd\u7ebd\u7ea6\u7684\u5ba2\u6237\u70b9\u4e0b\u9f20\u6807\uff0c` },
  { idx: 3, start: 14.28, dur: 2.52, hanzi: `\u5c31\u4e0b\u4e86\u8ba2\u5355\u8d2d\u4e70\u5317\u4eac\u5236\u9020\u7684\u7535\u5b50\u4ea7\u54c1\uff0c` },
  { idx: 4, start: 17.1, dur: 2.58, hanzi: `\u51e0\u5929\u5185\u5c31\u901a\u8fc7\u8d27\u8fd0\u98de\u673a\u6216\u662f\u6d77\u8fd0\u96c6\u88c5\u7bb1` },
  { idx: 5, start: 19.86, dur: 1.98, hanzi: `\u628a\u8d27\u7269\u4ece\u5927\u6d0b\u7684\u4e00\u7aef\u8fd0\u5230\u4e86\u53e6\u4e00\u7aef\u3002` },
  { idx: 6, start: 22.08, dur: 2.88, hanzi: `\u5f53\u4eca\u5168\u7403\u7684\u8d27\u7269\u548c\u4fe1\u606f\u6d41\u52a8\u7684\u901f\u5ea6\u548c\u603b\u91cf\uff0c` },
  { idx: 7, start: 25.2, dur: 1.2, hanzi: `\u90fd\u662f\u53f2\u65e0\u524d\u4f8b\u7684\u3002` },
  { idx: 8, start: 26.58, dur: 3.84, hanzi: `\u4f46\u662f\u5168\u7403\u5546\u54c1\u4ea4\u6d41\u7684\u5386\u53f2\u8981\u6bd4\u6211\u4eec\u60f3\u8c61\u7684\u53e4\u8001\u7684\u591a\uff0c` },
  { idx: 9, start: 31.38, dur: 2.22, hanzi: `2000\u5e74\u524d\uff0c\u6cbf\u7740\u4e00\u67615000\u82f1\u91cc\u957f\u7684\u9053\u8def\uff0c` },
  { idx: 10, start: 34.02, dur: 2.28, hanzi: `\u5373\u8457\u540d\u7684\u4e1d\u7ef8\u4e4b\u8def\uff0c\u8fd9\u4e00\u6d3b\u52a8\u5c31\u5df2\u7ecf\u5f00\u59cb\u3002` },
  { idx: 11, start: 36.84, dur: 1.68, hanzi: `\u4e1d\u7ef8\u4e4b\u8def\u5e76\u4e0d\u53ea\u662f\u4e00\u6761\u9053\u8def\uff0c` },
  { idx: 12, start: 38.88, dur: 1.74, hanzi: `\u800c\u662f\u8bb8\u591a\u4ea4\u9519\u7eb5\u6a2a\u7684\u8def\u7ebf\u3002` },
  { idx: 13, start: 40.8, dur: 2.64, hanzi: `\u8fd9\u4e9b\u8def\u7ebf\u662f\u5728\u51e0\u4e2a\u4e16\u7eaa\u4e2d\u9010\u6e10\u51fa\u73b0\u7684\uff0c` },
  { idx: 14, start: 43.8, dur: 2.16, hanzi: `\u4e00\u6761\u6761\u7684\u8def\u7ebf\u901a\u5411\u4e0d\u540c\u7684\u6816\u5c45\u5730\uff0c` },
  { idx: 15, start: 46.08, dur: 1.68, hanzi: `\u4e5f\u5c06\u5b83\u4eec\u76f8\u4e92\u8fde\u63a5\u5728\u4e00\u8d77\u3002` },
  { idx: 16, start: 48.12, dur: 2.76, hanzi: `\u6700\u539f\u59cb\u7684\u519c\u4e1a\u6587\u660e\u53d1\u6e90\u4e8e\u504f\u8fdc\u7684\uff0c` },
  { idx: 17, start: 51.18, dur: 0.96, hanzi: `\u80a5\u6c83\u7684\u6cb3\u8c37\u4e4b\u4e2d\uff0c` },
  { idx: 18, start: 52.32, dur: 2.4, hanzi: `\u5468\u56f4\u5730\u52bf\u7684\u4e0d\u4fbf\u4ee5\u53ca\u5bf9\u672a\u77e5\u7684\u6050\u60e7` },
  { idx: 19, start: 55.14, dur: 1.26, hanzi: `\u963b\u788d\u4e86\u5f53\u5730\u4eba\u7684\u4ea4\u5f80\u3002` },
  { idx: 20, start: 56.64, dur: 1.98, hanzi: `\u5f53\u5730\u4eba\u5728\u8fd9\u91cc\u5c45\u4f4f\u8fc7\u4e00\u6bb5\u65f6\u95f4\u540e\uff0c` },
  { idx: 21, start: 58.86, dur: 3.6, hanzi: `\u4ed6\u4eec\u53d1\u73b0\u4ed6\u4eec\u5728\u5e72\u65f1\u7684\u6c99\u6f20\u548c\u8fb9\u754c\u5468\u56f4\u6240\u4f4f\u7740\u7684\uff0c` },
  { idx: 22, start: 62.58, dur: 1.5, hanzi: `\u4e0d\u662f\u6c11\u95f4\u4f20\u8bf4\u91cc\u7684\u9b54\u9b3c\uff0c` },
  { idx: 23, start: 64.26, dur: 1.56, hanzi: `\u800c\u662f\u9a6c\u80cc\u4e0a\u7684\u6e38\u7267\u90e8\u843d\u3002` },
  { idx: 24, start: 66.72, dur: 2.52, hanzi: `\u4ece\u8499\u53e4\u5230\u5308\u7259\u5229\u904d\u5e03\u7684\u897f\u585e\u4e9a\u4eba` },
  { idx: 25, start: 69.66, dur: 1.98, hanzi: `\u65e9\u5c31\u8ddf\u5e0c\u814a\uff0c\u57c3\u53ca\uff0c\u5370\u5ea6` },
  { idx: 26, start: 71.94, dur: 1.2, hanzi: `\u4ee5\u53ca\u4e2d\u56fd\u6709\u6240\u63a5\u89e6\u3002` },
  { idx: 27, start: 73.5, dur: 2.1, hanzi: `\u8fd9\u4e9b\u63a5\u89e6\u901a\u5e38\u90fd\u4e0d\u662f\u548c\u5e73\u7684\uff0c` },
  { idx: 28, start: 75.52, dur: 1.9, hanzi: `\u4f46\u5373\u4fbf\u662f\u901a\u8fc7\u7a81\u88ad\uff0c\u6218\u4e89\uff0c` },
  { idx: 29, start: 77.42, dur: 2.15, hanzi: `\u8d38\u6613\uff0c\u4ee5\u53ca\u4ee5\u4fdd\u62a4\u5f80\u6765\u5546\u4eba\u4e3a\u6761\u4ef6` },
  { idx: 30, start: 79.57, dur: 1.24, hanzi: `\u589e\u6536\u7a0e\u52a1\uff0c` },
  { idx: 31, start: 84.57, dur: 2.97, hanzi: `\u6e38\u7267\u6c11\u65cf\u5c06\u8d27\u7269\uff0c\u601d\u60f3\u548c\u6280\u672f` },
  { idx: 32, start: 82.62, dur: 2.34, hanzi: `\u6269\u6563\u5230\u4e86\u90a3\u4e9b\u6ca1\u6709\u76f4\u63a5\u63a5\u89e6\u7684\u6587\u660e\u4e4b\u95f4\u3002` },
  { idx: 33, start: 88.5, dur: 1.62, hanzi: `\u5728\u8fd9\u4e2a\u4e0d\u65ad\u6269\u5927\u7684\u7f51\u7edc\u5f53\u4e2d\uff0c` },
  { idx: 34, start: 90.48, dur: 2.58, hanzi: `\u6700\u91cd\u8981\u7684\u4e00\u6761\u5c31\u8981\u6570\u6ce2\u65af\u5fa1\u9053\u4e86\u3002` },
  { idx: 35, start: 93, dur: 4.02, hanzi: `\u8fd9\u6761\u5fa1\u9053\u662f\u5728\u516c\u5143\u524d\u4e94\u4e16\u7eaa\uff0c\u7531\u5927\u6d41\u58eb\u4e00\u4e16\u5b8c\u6210\u7684\u3002` },
  { idx: 36, start: 97.32, dur: 4.26, hanzi: `\u5b83\u4ece\u5e95\u683c\u91cc\u65af\u6cb3\u4e00\u76f4\u5ef6\u7ef5\u81f3\u7231\u7434\u6d77\uff0c\u5168\u957f\u7ea62000\u82f1\u91cc\u3002` },
  { idx: 37, start: 101.88, dur: 2.76, hanzi: `\u8d27\u7269\u548c\u4fe1\u606f\u5728\u5176\u4e2d\u7ee7\u70b9\u901a\u884c\u6240\u9700\u7684\u65f6\u95f4` },
  { idx: 38, start: 105, dur: 2.34, hanzi: `\u4ec5\u662f\u5355\u4e2a\u65c5\u5ba2\u6240\u9700\u65f6\u95f4\u7684\u5341\u5206\u4e4b\u4e00\u3002` },
  { idx: 39, start: 108.06, dur: 2.34, hanzi: `\u968f\u540e\u4e9a\u5386\u5c71\u5927\u5927\u5e1d\u5f81\u670d\u4e86\u6ce2\u65af\uff0c` },
  { idx: 40, start: 110.7, dur: 4.26, hanzi: `\u901a\u8fc7\u5360\u9886\u4f8b\u5982\u6492\u9a6c\u5c14\u7f55\u8fd9\u79cd\u57ce\u5e02\uff0c\u5176\u7586\u57df\u4e00\u76f4\u6269\u5c55\u5230\u4e86\u4e2d\u4e9a\uff0c` },
  { idx: 41, start: 115.26, dur: 2.88, hanzi: `\u6b64\u5916\u4ed6\u8fd8\u5efa\u7acb\u4e86\u4f8b\u5982\u82e6\u76cf\u57ce\u8fd9\u6837\u65b0\u7684\u57ce\u6c60\uff0c` },
  { idx: 42, start: 118.62, dur: 4.02, hanzi: `\u5e0c\u814a\uff0c\u57c3\u53ca\uff0c\u6ce2\u65af\u4ee5\u53ca\u5370\u5ea6\u8fd9\u4e9b\u56fd\u5bb6\u7684\u6587\u660e\u548c\u8d38\u6613\u7f51\u7edc` },
  { idx: 43, start: 123.06, dur: 2.22, hanzi: `\u5411\u4e1c\u5ef6\u4f38\u7684\u7a0b\u5ea6\u8fbe\u5230\u4e86\u5386\u53f2\u4e4b\u6700\uff0c` },
  { idx: 44, start: 125.58, dur: 2.94, hanzi: `\u8fd9\u4e3a\u4e2d\u56fd\u548c\u897f\u65b9\u4e4b\u95f4\u7684\u6c9f\u901a\u6865\u6881\u6253\u4e0b\u4e86\u57fa\u7840\u3002` },
  { idx: 45, start: 129, dur: 1.62, hanzi: `\u76f4\u5230\u516c\u5143\u524d\u4e8c\u4e16\u7eaa\uff0c` },
  { idx: 46, start: 130.56, dur: 1.44, hanzi: `\u4e00\u4f4d\u540d\u53eb\u5f20\u8b07\u7684\u5927\u4f7f\uff0c` },
  { idx: 47, start: 132.24, dur: 2.22, hanzi: `\u88ab\u6d3e\u5f80\u524d\u53bb\u8ddf\u897f\u65b9\u7684\u6e38\u7267\u90e8\u843d\u8c08\u5224\uff0c` },
  { idx: 48, start: 134.7, dur: 2.82, hanzi: `\u8fd9\u4f4d\u5927\u4f7f\u56de\u5230\u4e2d\u56fd\u4e4b\u540e\uff0c\u5411\u5f53\u65f6\u7684\u6c49\u671d\u7687\u5e1d` },
  { idx: 49, start: 137.7, dur: 3.12, hanzi: `\u8bb2\u8ff0\u4e86\u8bb8\u591a\u6709\u5173\u5176\u8fb9\u754c\u897f\u90e8\u5730\u533a\u53e4\u8001\u7684\u6587\u660e\uff0c` },
  { idx: 50, start: 141.24, dur: 2.04, hanzi: `\u84ec\u52c3\u7684\u8d38\u6613\uff0c\u4ee5\u53ca\u5947\u5f02\u7684\u8d27\u7269\u7684\u6545\u4e8b\u3002` },
  { idx: 51, start: 143.7, dur: 3.6, hanzi: `\u63a5\u7740\u8bb8\u591a\u5927\u4f7f\u3001\u5546\u4eba\u76f8\u7ee7\u88ab\u6d3e\u5f80\u6ce2\u65af\u548c\u5370\u5ea6\uff0c` },
  { idx: 52, start: 147.54, dur: 2.22, hanzi: `\u7528\u4e1d\u7ef8\u548c\u7389\u4ea4\u6362\u4ed6\u4eec\u7684\u9a6c\u548c\u68c9\u82b1\u3002` },
  { idx: 53, start: 150.36, dur: 3, hanzi: `\u5f53\u65f6\u968f\u4ece\u7684\u8fd8\u6709\u519b\u961f\uff0c\u4ee5\u4fdd\u8bc1\u4ed6\u4eec\u65c5\u9014\u7684\u5b89\u5168\u3002` },
  { idx: 54, start: 153.84, dur: 2.4, hanzi: `\u4e1c\u65b9\u548c\u897f\u65b9\u4e4b\u95f4\u7684\u9053\u8def\u9010\u6e10\u5f62\u6210\u4e86` },
  { idx: 55, start: 156.36, dur: 1.32, hanzi: `\u4e00\u4e2a\u8de8\u6b27\u4e9a\u7684\u7f51\u7edc\uff0c` },
  { idx: 56, start: 157.92, dur: 3.06, hanzi: `\u8fd9\u4e00\u7f51\u7edc\u4f7f\u5f97\u6b27\u4e9a\u4e4b\u95f4\u7684\u6587\u5316\u548c\u5546\u4e1a\u4ea4\u5f80\u7a0b\u5ea6` },
  { idx: 57, start: 161.22, dur: 1.62, hanzi: `\u8fbe\u5230\u4e86\u5f53\u65f6\u7684\u5386\u53f2\u4e4b\u6700\u3002` },
  { idx: 58, start: 163.26, dur: 1.44, hanzi: `\u4e2d\u56fd\u7684\u8d27\u7269\u6765\u5230\u4e86\u7f57\u9a6c\uff0c` },
  { idx: 59, start: 165.06, dur: 3.96, hanzi: `\u9020\u6210\u5927\u91cf\u7684\u9ec4\u91d1\u5916\u6d41\uff0c\u56e0\u6b64\u7f57\u9a6c\u7981\u6b62\u4e86\u4e1d\u7ef8\u4ea4\u6613\u3002` },
  { idx: 60, start: 169.44, dur: 2.34, hanzi: `\u7f57\u9a6c\u7684\u73bb\u7483\u5668\u5177\u5728\u4e2d\u56fd\u4e5f\u5341\u5206\u53d7\u6b22\u8fce\uff0c` },
  { idx: 61, start: 173.64, dur: 0.9, hanzi: `\u4e2d\u4e9a\u7684\u8fdc\u5f81\u519b` },
  { idx: 62, start: 174.66, dur: 1.86, hanzi: `\u770b\u5230\u4e86\u4e2d\u56fd\u548c\u7f57\u9a6c\u519b\u961f\u7684\u76f8\u9047\u3002` },
  { idx: 63, start: 178.38, dur: 0.72, hanzi: `\u77f3\u5f13\u6280\u672f` },
  { idx: 64, start: 179.34, dur: 0.6, hanzi: `\u4f20\u5230\u897f\u65b9\u3002` },
  { idx: 65, start: 182.4, dur: 1.32, hanzi: `\u5bf9\u4e8e\u5f02\u56fd\u8d27\u7269\u7684\u9700\u6c42\uff0c` },
  { idx: 66, start: 184.2, dur: 1.02, hanzi: `\u8d38\u6613\u5e26\u6765\u7684\u5229\u76ca\uff0c` },
  { idx: 67, start: 185.46, dur: 2.22, hanzi: `\u4f7f\u5f97\u8fd9\u6761\u4e1d\u7ef8\u4e4b\u8def\u4e00\u76f4\u4fdd\u5b58\u5b8c\u597d\uff0c` },
  { idx: 68, start: 188.1, dur: 1.68, hanzi: `\u5c3d\u7ba1\u7f57\u9a6c\u5e1d\u56fd\u5206\u5d29\u79bb\u6790\uff0c` },
  { idx: 69, start: 190.08, dur: 1.68, hanzi: `\u4e2d\u56fd\u7684\u671d\u4ee3\u76db\u8870\u5174\u5e9f\u3002` },
  { idx: 70, start: 192.24, dur: 3.78, hanzi: `\u5373\u4f7f\u662f\u90a3\u4e9b\u4ee5\u62a2\u52ab\u548c\u63a0\u593a\u81ed\u540d\u662d\u8457\u7684\u8499\u53e4\u56e4\u79ef\u5546\u4eba\uff0c` },
  { idx: 71, start: 196.26, dur: 3.18, hanzi: `\u4e5f\u79ef\u6781\u5730\u4fdd\u62a4\u8fd9\u4e9b\u8d38\u6613\u901a\u9053\uff0c\u800c\u4e0d\u662f\u7834\u574f\u5b83\u4eec\u3002` },
  { idx: 72, start: 200.22, dur: 2.04, hanzi: `\u968f\u7740\u5546\u54c1\u7ecf\u6d4e\u7684\u53d1\u8fbe\uff0c\u8fd9\u6761\u9053\u8def` },
  { idx: 73, start: 202.56, dur: 4.14, hanzi: `\u540c\u65f6\u4e5f\u4f7f\u5f97\u6587\u5316\uff0c\u521b\u65b0\u6280\u672f\uff0c\u601d\u60f3\u548c\u8bed\u8a00\u5f97\u4ee5\u6d41\u901a\u3002` },
  { idx: 74, start: 207.48, dur: 2.88, hanzi: `\u53d1\u6e90\u4e8e\u5370\u5ea6\uff0c\u4f5b\u6559\u4f20\u64ad\u5230\u4e86\u4e2d\u56fd\u548c\u65e5\u672c` },
  { idx: 75, start: 210.9, dur: 1.8, hanzi: `\u6210\u4e3a\u4e9a\u6d32\u5730\u533a\u6700\u76db\u884c\u7684\u5b97\u6559\u3002` },
  { idx: 76, start: 213.54, dur: 2.28, hanzi: `\u4f0a\u65af\u5170\u6559\u4ece\u963f\u62c9\u4f2f\u534a\u5c9b\u4f20\u5230\u5357\u4e9a\uff0c` },
  { idx: 77, start: 216.36, dur: 1.14, hanzi: `\u548c\u5f53\u5730\u7684\u4fe1\u4ef0\u878d\u5408` },
  { idx: 78, start: 217.68, dur: 2.52, hanzi: `\u5f62\u6210\u65b0\u7684\u5b97\u6559\uff0c\u6bd4\u5982\u9521\u514b\u6559\u3002` },
  { idx: 79, start: 221.58, dur: 1.44, hanzi: `\u706b\u836f\u4ece\u4e2d\u56fd\u4f20\u5230\u4e2d\u4e1c` },
  { idx: 80, start: 223.62, dur: 3.84, hanzi: `\u5f62\u5851\u4e86\u571f\u8033\u5176\u5e1d\u56fd\uff0c\u8428\u6cd5\u7ef4\u5e1d\u56fd\uff0c\u4e0e\u9a6c\u62c9\u5854\u5e1d\u56fd\u7684\u672a\u6765\u3002` },
  { idx: 81, start: 228.48, dur: 3.12, hanzi: `\u67d0\u79cd\u7a0b\u5ea6\u4e0a\u8bf4\uff0c\u4e1d\u7ef8\u4e4b\u8def\u6210\u529f\u5730\u7ec8\u7ed3\u4e86\u81ea\u5df1\u3002` },
  { idx: 82, start: 232.32, dur: 2.16, hanzi: `\u65b0\u7684\u822a\u6d77\u6280\u672f\uff0c\u50cf\u662f\u78c1\u7f57\u76d8\uff0c` },
  { idx: 83, start: 235.02, dur: 3.18, hanzi: `\u4f20\u5f80\u6b27\u6d32\uff0c\u4f7f\u5f97\u9646\u5730\u4e0a\u7684\u957f\u7a0b\u516c\u8def\u88ab\u6dd8\u6c70\u4e86\u3002` },
  { idx: 84, start: 239.34, dur: 1.92, hanzi: `\u4e0e\u6b64\u540c\u65f6\uff0c\u5143\u671d\u74e6\u89e3\u540e\uff0c` },
  { idx: 85, start: 241.56, dur: 1.74, hanzi: `\u4e2d\u56fd\u4ece\u56fd\u9645\u8d38\u6613\u7248\u56fe\u6d88\u5931\u3002` },
  { idx: 86, start: 244.5, dur: 2.46, hanzi: `\u5373\u4fbf\u65e7\u7684\u9053\u8def\u548c\u8d38\u6613\u7f51\u7edc\u6ca1\u80fd\u957f\u4e45\uff0c` },
  { idx: 87, start: 247.26, dur: 1.32, hanzi: `\u5b83\u4eec\u4e5f\u6c38\u4e45\u6539\u53d8\u4e86\u4e16\u754c\uff0c` },
  { idx: 88, start: 249.18, dur: 1.26, hanzi: `\u6ca1\u6709\u5012\u9000\u7684\u53ef\u80fd\u4e86\u3002` },
  { idx: 89, start: 251.04, dur: 1.92, hanzi: `\u6b27\u6d32\u4eba\u5bfb\u627e\u65b0\u7684\u6d77\u4e0a\u822a\u9053` },
  { idx: 90, start: 253.56, dur: 1.44, hanzi: `\u60f3\u8981\u5bfb\u627e\u4e1c\u4e9a\u7684\u8d22\u5bcc` },
  { idx: 91, start: 255.84, dur: 1.68, hanzi: `\u5bfc\u81f4\u4e86\u5176\u5728\u975e\u6d32\u548c\u7f8e\u6d32\u7684` },
  { idx: 92, start: 257.64, dur: 0.72, hanzi: `\u63a2\u7d22\u548c\u6269\u5f20\u3002` },
  { idx: 93, start: 259.92, dur: 4.02, hanzi: `\u4eca\u5929\uff0c\u5168\u7403\u5404\u56fd\u76f8\u4e92\u8054\u7edc\u65e0\u65f6\u65e0\u523b\u4e0d\u5728\u5f71\u54cd\u7740\u6211\u4eec\u7684\u751f\u6d3b\u3002` },
  { idx: 94, start: 264.9, dur: 2.34, hanzi: `\u52a0\u62ff\u5927\u6d88\u8d39\u8005\u8d2d\u4e70\u5728\u5b5f\u52a0\u62c9\u5236\u4f5c\u7684T\u6064\uff0c` },
  { idx: 95, start: 268.38, dur: 1.8, hanzi: `\u65e5\u672c\u89c2\u4f17\u89c2\u770b\u82f1\u56fd\u7535\u89c6\u8282\u76ee\uff0c` },
  { idx: 96, start: 271.08, dur: 2.1, hanzi: `\u7a81\u5c3c\u65af\u4eba\u4f7f\u7528\u7f8e\u56fd\u7684\u8f6f\u4ef6\u6765\u7ec4\u7ec7\u9769\u547d\u3002` },
  { idx: 97, start: 274.74, dur: 3.06, hanzi: `\u5168\u7403\u5316\u5bf9\u6587\u5316\u548c\u7ecf\u6d4e\u7684\u5f71\u54cd\u662f\u65e0\u53ef\u4e89\u8bae\u7684\u3002` },
  { idx: 98, start: 278.94, dur: 1.62, hanzi: `\u4f46\u968f\u4e4b\u800c\u6765\u7684\u597d\u5904\u4e0e\u7f3a\u70b9\uff0c` },
  { idx: 99, start: 280.86, dur: 1.32, hanzi: `\u4e5f\u4e0d\u662f\u65b0\u9c9c\u4e8b\u4e86\u3002` },
  { idx: 100, start: 284.88, dur: 2.28, hanzi: `\u5c3d\u7ba1\u5c71\u5ddd\uff0c\u6c99\u6f20\uff0c\u6d77\u6d0b` },
  { idx: 101, start: 283.68, dur: 1.26, hanzi: `\u90a3\u4e9b\u66fe\u7ecf\u9694\u65ad\u6211\u4eec` },
  { idx: 102, start: 287.79, dur: 1.05, hanzi: `\u88ab\u8d85\u97f3\u901f\u673a\u68b0\uff0c` },
  { idx: 103, start: 290.04, dur: 0.66, hanzi: `\u6d77\u5e95\u7535\u7f06` },
  { idx: 104, start: 291.58, dur: 2.21, hanzi: `\u548c\u7a7f\u8d8a\u7a7a\u95f4\u7684\u4fe1\u53f7\u4f20\u8f93\u5305\u56f4\uff0c` },
  { idx: 105, start: 293.58, dur: 1.68, hanzi: `\u4e0d\u518d\u662f\u5546\u961f\u8dcb\u6d89\u6570\u6708\u4e86\uff0c` },
  { idx: 106, start: 296.12, dur: 1.75, hanzi: `\u4e0a\u8ff0\u4e00\u5207\u90fd\u4e0d\u4f1a\u53d1\u751f` },
  { idx: 107, start: 295.62, dur: 1.41, hanzi: `\u5982\u679c\u6ca1\u6709\u5148\u8fdb\u7684\u6587\u5316` },
  { idx: 108, start: 298.92, dur: 2.28, hanzi: `\u8fd9\u6837\u7684\u5148\u8fdb\u6587\u5316\u521b\u9020\u4e86\u4e1d\u7ef8\u4e4b\u8def\uff1a` },
  { idx: 109, start: 301.44, dur: 2.46, hanzi: `\u4e16\u754c\u4e0a\u7b2c\u4e00\u4e2a\u8fde\u63a5\u4e16\u754c\u7684\u4e92\u8054\u7f51\u3002` },
];

export const DICTATION_VIDEOS: DictationVideo[] = [
  {
    id: "teded-silk-road-k-jjFZQNw",
    youtubeId: "k-jjFZQNw_Y",
    title: `\u4e1d\u7ef8\u4e4b\u8def\uff1a\u8fde\u7ed3\u53e4\u4ee3\u4e16\u754c\u7684\u8d38\u6613\u4e4b\u8def`,
    titleVi: "Con đường tơ lụa: Con đường thương mại kết nối thế giới cổ đại",
    level: "advanced",
    category: "discovery",
    durationLabel: "05:23",
    languageCode: "zh-Hans",
    isAutoGenerated: false,
    segments: SILK_ROAD_SEGMENTS,
  },
];
